declare module "*.module.scss"
declare module "country-currency-map"
declare module "qrcode.react"
declare module "react-numeral"
declare module "numeral"
declare module "reat-chartjs-2"
declare module "chart.js"
declare module "chartjs-plugin-datalabels"
